name: "Tests: E2E"

on: [pull_request]

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: [18, 20, 22]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            commandPrefix: 'xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24 +extension GLX +render -noreset" --'
          - os: windows-latest
            commandPrefix: ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install system dependencies (Ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm2 \
            libxkbcommon-dev \
            libxcomposite-dev \
            libxdamage-dev \
            libxrandr-dev \
            libgbm-dev \
            libxss-dev \
            libasound2-dev
      - name: Install dependencies
        run: npm ci && cd example-project && npm ci
      - name: Lint
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: npm run lint
      - name: e2e tests
        run: ${{ matrix.commandPrefix }} npm test



